# what i want workflow to do
name: Testing 
# when should this workflow run
on: push

jobs:
    test_project:
        # what sort of machine is it going to run on
        runs-on: ubuntu-latest
        # what steps should happen
        steps:
          #this action is going to check out my code in the Git repository and allow me to run programs that operate on the code
        - uses: actions/checkout@v2
        - name: Run Django unit tests
          run: |
            pip3 install --user django
            python3 manage.py tset
